#!/bin/bash
# Huntress Attack Machine Entrypoint
#
# Generates Squid ACL from HUNTRESS_ALLOWED_DOMAINS, starts the proxy,
# and optionally starts interactsh-client for OOB detection.
#
# Environment:
#   HUNTRESS_ALLOWED_DOMAINS — comma-separated list of in-scope domains
#
# The Squid proxy enforces default-deny: only domains listed in the ACL
# are reachable. All outgoing HTTP requests include X-Huntress-Agent header.

set -e

# ── Generate Squid ACL from allowed domains ──────────────────────────────────

ALLOWED_DOMAINS="${HUNTRESS_ALLOWED_DOMAINS:-}"

if [ -z "$ALLOWED_DOMAINS" ]; then
    echo "[FATAL] HUNTRESS_ALLOWED_DOMAINS is not set. Cannot start without scope."
    exit 1
fi

# Write ACL file
ACL_FILE="/etc/squid/conf.d/huntress_acl.conf"

echo "# Auto-generated by Huntress entrypoint — DO NOT EDIT" > "$ACL_FILE"
echo "# Allowed domains: $ALLOWED_DOMAINS" >> "$ACL_FILE"
echo "" >> "$ACL_FILE"

# Parse comma-separated domains into ACL entries
IFS=',' read -ra DOMAINS <<< "$ALLOWED_DOMAINS"
for domain in "${DOMAINS[@]}"; do
    domain=$(echo "$domain" | xargs)  # Trim whitespace
    if [ -n "$domain" ]; then
        # Support wildcard domains (*.example.com -> .example.com)
        if [[ "$domain" == \** ]]; then
            domain="${domain#\*}"
        fi
        echo "acl huntress_scope dstdomain $domain" >> "$ACL_FILE"
    fi
done

echo "" >> "$ACL_FILE"
echo "# Default-deny: only allow in-scope domains" >> "$ACL_FILE"
echo "http_access allow huntress_scope" >> "$ACL_FILE"
echo "http_access deny all" >> "$ACL_FILE"

# Write main Squid config
cat > /etc/squid/squid.conf << 'SQUIDCONF'
# Huntress scope-enforcing proxy
http_port 3128

# Include generated ACL
include /etc/squid/conf.d/huntress_acl.conf

# Add custom header to all requests
request_header_add X-Huntress-Agent "huntress-sandbox/1.0" all

# Minimal cache (we don't want caching for security testing)
cache deny all

# Logging
access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log

# PID file
pid_filename /var/run/squid.pid

# Disable ICP
icp_port 0

# Timeouts
connect_timeout 30 seconds
read_timeout 120 seconds
request_timeout 120 seconds

# DNS
dns_nameservers 1.1.1.1 8.8.8.8
SQUIDCONF

# ── Start Squid proxy ────────────────────────────────────────────────────────

echo "[*] Starting scope-enforcing Squid proxy..."
echo "[*] Allowed domains: $ALLOWED_DOMAINS"

# Initialize Squid cache directories
squid -z -N 2>/dev/null || true

# Start Squid in the background
squid -N &
SQUID_PID=$!

# Wait for Squid to be ready
for i in $(seq 1 10); do
    if curl -s -o /dev/null -x http://127.0.0.1:3128 http://localhost 2>/dev/null; then
        break
    fi
    sleep 0.5
done

echo "[+] Squid proxy started (PID: $SQUID_PID)"

# ── Start interactsh-client if available ──────────────────────────────────────

if command -v interactsh-client &> /dev/null; then
    echo "[*] Starting interactsh-client for OOB detection..."
    interactsh-client -v 2>/dev/null &
    echo "[+] interactsh-client started"
fi

# ── Execute the command ──────────────────────────────────────────────────────

echo "[*] Executing: $@"
exec "$@"
