/**
 * WAF Detection & Adaptive Bypass (Phase 20G)
 *
 * Detects Web Application Firewalls by analyzing response headers, cookies,
 * and block page signatures. Most production HackerOne targets sit behind WAFs
 * (Cloudflare, AWS WAF, Akamai, Imperva). Without WAF detection, agent payloads
 * are silently blocked and agents waste iterations.
 *
 * Detection uses three signals:
 * 1. Response header signatures (cf-ray, x-akamai-transformed, etc.)
 * 2. Cookie patterns (__cfduid, incap_ses_*, etc.)
 * 3. Block page analysis (send known-bad payload, check 403 response body)
 */

import type { HttpClient, HttpResponse } from '../http/request_engine';

// ─── Types ───────────────────────────────────────────────────────────────────

export type WAFVendor =
  | 'cloudflare' | 'aws_waf' | 'akamai' | 'imperva'
  | 'sucuri' | 'f5_bigip' | 'barracuda' | 'fortinet'
  | 'modsecurity' | 'wordfence' | 'unknown' | 'none';

export interface WAFDetectionResult {
  detected: boolean;
  vendor: WAFVendor;
  confidence: number;
  evidence: string[];
  blockStatusCode?: number;
  blockPageSignature?: string;
}

// ─── Header Signatures ──────────────────────────────────────────────────────

interface HeaderSignature {
  header: string;
  pattern: RegExp;
}

const WAF_HEADER_SIGNATURES: Record<string, HeaderSignature[]> = {
  cloudflare: [
    { header: 'server', pattern: /cloudflare/i },
    { header: 'cf-ray', pattern: /.+/ },
    { header: 'cf-cache-status', pattern: /.+/ },
  ],
  aws_waf: [
    { header: 'x-amzn-requestid', pattern: /.+/ },
    { header: 'x-amz-cf-id', pattern: /.+/ },
  ],
  akamai: [
    { header: 'x-akamai-transformed', pattern: /.+/ },
    { header: 'server', pattern: /AkamaiGHost/i },
  ],
  imperva: [
    { header: 'x-iinfo', pattern: /.+/ },
    { header: 'x-cdn', pattern: /Imperva|Incapsula/i },
  ],
  sucuri: [
    { header: 'x-sucuri-id', pattern: /.+/ },
    { header: 'server', pattern: /Sucuri/i },
  ],
  f5_bigip: [
    { header: 'server', pattern: /BigIP|BIG-IP|F5/i },
    { header: 'x-wa-info', pattern: /.+/ },
  ],
  barracuda: [
    { header: 'server', pattern: /Barracuda/i },
  ],
  fortinet: [
    { header: 'server', pattern: /FortiWeb/i },
  ],
  modsecurity: [
    { header: 'server', pattern: /mod_security|NOYB/i },
  ],
  wordfence: [
    { header: 'x-wordfence', pattern: /.+/ },
  ],
};

// ─── Cookie Signatures ───────────────────────────────────────────────────────

const WAF_COOKIE_PATTERNS: Record<string, RegExp[]> = {
  cloudflare: [/^__cfduid$/i, /^__cf_bm$/i, /^cf_clearance$/i],
  imperva: [/^incap_ses_/i, /^visid_incap_/i, /^nlbi_/i],
  sucuri: [/^sucuri_cloudproxy_uuid_/i],
  f5_bigip: [/^TS[0-9a-f]{8}$/i, /^BIGipServer/i],
  barracuda: [/^barra_counter_session$/i],
};

// ─── Block Page Patterns ─────────────────────────────────────────────────────

const BLOCK_PAGE_PATTERNS: Record<string, RegExp[]> = {
  cloudflare: [/Attention Required/i, /Cloudflare Ray ID/i, /cf-error-details/i, /cf-browser-verification/i],
  aws_waf: [/Request blocked/i, /aws.*waf/i, /automated access to this page/i],
  akamai: [/Access Denied.*Akamai/i, /Reference.*#\d+\.\w+/i, /AkamaiGHost/i],
  imperva: [/Incapsula incident/i, /Request unsuccessful/i, /powered by Incapsula/i],
  sucuri: [/sucuri.*firewall/i, /blocked by Sucuri/i, /Sucuri WebSite Firewall/i],
  modsecurity: [/ModSecurity/i, /not acceptable/i, /Security Rule/i],
  wordfence: [/blocked by Wordfence/i, /generated by Wordfence/i, /Wordfence Security/i],
  f5_bigip: [/The requested URL was rejected/i, /Please consult with your administrator/i],
  barracuda: [/You are being blocked/i, /Barracuda/i],
  fortinet: [/FortiGuard/i, /FortiWeb/i, /web filter/i],
};

// ─── WAF Detector ────────────────────────────────────────────────────────────

export class WAFDetector {
  private httpClient: HttpClient;

  constructor(httpClient: HttpClient) {
    this.httpClient = httpClient;
  }

  /** Detect WAF by analyzing response headers, cookies, and optionally block pages */
  async detect(targetUrl: string): Promise<WAFDetectionResult> {
    const evidence: string[] = [];
    const vendorScores: Record<string, number> = {};

    try {
      // Step 1: Send a clean GET request and analyze headers/cookies
      const cleanResponse = await this.httpClient.request({
        url: targetUrl,
        method: 'GET',
      });

      // Analyze headers
      const headerResults = this.analyzeHeaders(cleanResponse);
      for (const [vendor, score, ev] of headerResults) {
        vendorScores[vendor] = (vendorScores[vendor] ?? 0) + score;
        evidence.push(ev);
      }

      // Analyze cookies
      const cookieResults = this.analyzeCookies(cleanResponse);
      for (const [vendor, score, ev] of cookieResults) {
        vendorScores[vendor] = (vendorScores[vendor] ?? 0) + score;
        evidence.push(ev);
      }
    } catch {
      // Request failed — may still be WAF-related, continue with probe
    }

    // Step 2: Probe with a known-bad payload to trigger block page
    try {
      const probeResult = await this.probeWithPayload(targetUrl);
      if (probeResult.detected) {
        const vendor = probeResult.vendor;
        vendorScores[vendor] = (vendorScores[vendor] ?? 0) + 0.5;
        evidence.push(...probeResult.evidence);

        if (probeResult.blockStatusCode) {
          evidence.push(`Block status code: ${probeResult.blockStatusCode}`);
        }
      }
    } catch {
      // Probe failed — proceed with header-only analysis
    }

    // Determine best-match vendor
    const sortedVendors = Object.entries(vendorScores)
      .sort(([, a], [, b]) => b - a);

    if (sortedVendors.length === 0) {
      return {
        detected: false,
        vendor: 'none',
        confidence: 0.9,
        evidence: ['No WAF signatures detected in headers, cookies, or block response'],
      };
    }

    const [bestVendor, bestScore] = sortedVendors[0];
    const confidence = Math.min(1.0, bestScore / 2.0);

    return {
      detected: true,
      vendor: bestVendor as WAFVendor,
      confidence,
      evidence,
    };
  }

  /** Send a known-bad payload and analyze the block response */
  async probeWithPayload(targetUrl: string): Promise<WAFDetectionResult> {
    const evidence: string[] = [];

    // Use a URL parameter that should trigger any WAF
    const separator = targetUrl.includes('?') ? '&' : '?';
    const probeUrl = `${targetUrl}${separator}huntress_waf_probe=<script>alert(1)</script>`;

    try {
      const response = await this.httpClient.request({
        url: probeUrl,
        method: 'GET',
      });

      // Check if we got a block response
      const isBlocked = response.status === 403 || response.status === 406 || response.status === 501;

      if (isBlocked) {
        // Analyze the block page for vendor signatures
        for (const [vendor, patterns] of Object.entries(BLOCK_PAGE_PATTERNS)) {
          for (const pattern of patterns) {
            if (pattern.test(response.body)) {
              evidence.push(`Block page matches ${vendor}: ${pattern.source}`);
              return {
                detected: true,
                vendor: vendor as WAFVendor,
                confidence: 0.85,
                evidence,
                blockStatusCode: response.status,
                blockPageSignature: pattern.source,
              };
            }
          }
        }

        // Got blocked but can't identify vendor
        evidence.push(`Blocked with status ${response.status} but no vendor-specific page signature`);
        return {
          detected: true,
          vendor: 'unknown',
          confidence: 0.5,
          evidence,
          blockStatusCode: response.status,
        };
      }

      // Not blocked — might still have WAF in detection-only mode
      return {
        detected: false,
        vendor: 'none',
        confidence: 0,
        evidence: ['Probe payload was not blocked'],
      };
    } catch {
      // Connection error might be WAF dropping the connection
      evidence.push('Connection dropped during probe — possible WAF connection reset');
      return {
        detected: true,
        vendor: 'unknown',
        confidence: 0.3,
        evidence,
      };
    }
  }

  // ─── Private Helpers ─────────────────────────────────────────────────────────

  private analyzeHeaders(response: HttpResponse): Array<[string, number, string]> {
    const results: Array<[string, number, string]> = [];
    const headers = response.headers;

    for (const [vendor, signatures] of Object.entries(WAF_HEADER_SIGNATURES)) {
      for (const sig of signatures) {
        const headerValue = headers[sig.header] ?? headers[sig.header.toLowerCase()];
        if (headerValue && sig.pattern.test(headerValue)) {
          results.push([vendor, 0.4, `Header ${sig.header}: ${headerValue} → ${vendor}`]);
        }
      }
    }

    return results;
  }

  private analyzeCookies(response: HttpResponse): Array<[string, number, string]> {
    const results: Array<[string, number, string]> = [];
    const cookies = response.cookies;

    for (const cookie of cookies) {
      for (const [vendor, patterns] of Object.entries(WAF_COOKIE_PATTERNS)) {
        for (const pattern of patterns) {
          if (pattern.test(cookie.name)) {
            results.push([vendor, 0.3, `Cookie ${cookie.name} → ${vendor}`]);
          }
        }
      }
    }

    return results;
  }
}
